name: api
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - click=8.1.3
  - flask=2.2.2
  - importlib-metadata=4.11.4
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsqlite=3.39.3
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - markupsafe=2.1.1
  - ncurses=6.3
  - numpy=1.23.2
  - openssl=3.0.5
  - pandas=1.4.4
  - pip=22.2.2
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.1.2
  - setuptools=65.3.0
  - tk=8.6.12
  - tzdata=2022c
  - werkzeug=2.2.2
  - wheel=0.37.1
  - xz=5.2.6
  - zipp=3.8.1
  - pip:
    - aniso8601==9.0.1
    - flask-restful==0.3.9
    - gunicorn==20.1.0
    - pytz==2022.2.1
    - six==1.16.0
